version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: deefacto-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: deefacto_db
      MYSQL_USER: deefacto
      MYSQL_PASSWORD: deefacto1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data: